title: ISV considerations for quota and capacity management in Azure
description: ISV guidance for Azure quota, capacity, and billing operations
theme: just-the-docs
color_scheme: dark
logo: "/assets/logo.svg"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
relative_links:
  enabled: true
  collections: false
