title: ISV Considerations for Quota and Capacity Management in Azure
description: ISV playbooks for Azure quota, capacity, and billing operations
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
relative_links:
  enabled: true
  collections: false
